### ISSUE TITLE
글 즐겨찾기 API를 추가하고 싶어요.

### ISSUE THREAD

**Issue by kcm1700** [snucse/snucse-api#2]
사용자는 글 스크랩, 기록 관리, 자주 접근할 자료, 공약(?) 등의 관리 등을 위해 필요해요.

즐겨찾기 구조, 어떻게 저장할지 등을 가볍게 논의해보고 싶네요.

일단 지금 있는 상태가 다음과 같다고 생각하는데, 맞나요.
- 테이블 구조는 존재 favorite_articles(user_id(int), article_id(int), timestamp) 
- 필요한 API는 결정된 것이 없음
- 단순한 model 뼈대는 존재
- view, controller 등은 없음

조금 확장해서 다음과 같은 구조를 만들고 싶어요.

- 얕은 디렉토리 구조 지원 (기존 구분자 기능은 불편했습니다)
- 별명 붙이기 기능 추가
- 순서를 제어 가능하거나, 별명 순으로 정렬해서 보여줄 것.

**Comment by operatz** [comment]
프로젝트가 현재 두 개로 나뉘어 있어 이슈는 snucse(구 snucse-frontend)로 일원화하기로 결정했습니다. 해당 내용은 snucse 프로젝트의 이슈로 제가 옮기겠습니다.
